# Generated by Django 4.1.2 on 2022-11-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_remove_invoice_line_five_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='line_one_quantity',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_one_unit_price',
        ),
    ]
