# Generated by Django 4.1.2 on 2022-11-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_remove_invoice_line_one_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='cgst',
            field=models.FloatField(blank=True, default=9, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sgst',
            field=models.FloatField(blank=True, default=9, null=True),
        ),
    ]
