# Generated by Django 4.1.2 on 2022-11-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_invoice_line_four_invoice_line_four_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='line_four_HSN',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='HSN no.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_four_serial',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Serial no.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_three_HSN',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='HSN no.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_three_serial',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Serial no.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_two_HSN',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='HSN no.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_two_serial',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Serial no.'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_four',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Product 3'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_three',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Product 2'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_two',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Product 1'),
        ),
    ]
