# Generated by Django 4.1.2 on 2022-11-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_invoice_line_four_hsn_invoice_line_four_serial_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='discount',
            new_name='line_four_discount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_one',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_one_total_price',
        ),
        migrations.AddField(
            model_name='invoice',
            name='address',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_three_discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_two_discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
