# Generated by Django 4.1.2 on 2022-11-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_rename_discount_invoice_line_four_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='subtotal',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
