# Generated by Django 4.1.2 on 2022-11-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_invoice_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='address',
            field=models.TextField(blank=True, default='', max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_four_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total '),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_four_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price '),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_three_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_three_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price '),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_two_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total '),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_two_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Phone number'),
        ),
    ]
