# Generated by Django 4.1.2 on 2022-11-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_alter_invoice_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='line_four_HSN',
            field=models.CharField(blank=True, default=0, max_length=20, null=True, verbose_name='HSN no.'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_four_serial',
            field=models.CharField(blank=True, default=0, max_length=20, null=True, verbose_name='Serial no.'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_three_HSN',
            field=models.CharField(blank=True, default=0, max_length=20, null=True, verbose_name='HSN no.'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_three_serial',
            field=models.CharField(blank=True, default=0, max_length=20, null=True, verbose_name='Serial no.'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_two_HSN',
            field=models.CharField(blank=True, default=0, max_length=20, null=True, verbose_name='HSN no.'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_two_serial',
            field=models.CharField(blank=True, default=0, max_length=20, null=True, verbose_name='Serial no.'),
        ),
    ]
