# Generated by Django 4.1.2 on 2022-10-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_inventoryitems_export_to_csv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_name', models.CharField(max_length=50)),
                ('cost_address', models.CharField(max_length=100)),
                ('cost_number', models.IntegerField(verbose_name=10)),
            ],
        ),
    ]
