# Generated by Django 4.1.2 on 2022-10-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_checkout_cost_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='discount',
            field=models.FloatField(default='0.00', max_length=10),
        ),
        migrations.AddField(
            model_name='checkout',
            name='export_to_csv',
            field=models.BooleanField(default=True),
        ),
    ]
