# Generated by Django 4.1.2 on 2022-10-31 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_checkout_discount_checkout_export_to_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='cost_number',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
