# Generated by Django 4.1.2 on 2022-10-31 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_inventoryitems_item_hsn_inventoryitems_item_serial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='cost_cgst',
            field=models.FloatField(default='0.00', max_length=10),
        ),
        migrations.AddField(
            model_name='checkout',
            name='cost_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='cost_sgst',
            field=models.FloatField(default='0.00', max_length=10),
        ),
        migrations.AlterField(
            model_name='inventoryitems',
            name='item_HSN',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryitems',
            name='item_serial',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryproducts',
            name='product_HSN',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryproducts',
            name='product_serial',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
