# Generated by Django 4.1.2 on 2022-10-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_checkoutitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitems',
            name='item_serial',
            field=models.CharField(default='0', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='inventoryproducts',
            name='product_serial',
            field=models.CharField(default='0', max_length=50, unique=True),
        ),
    ]
