# Generated by Django 4.1.2 on 2022-10-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_alter_inventoryitems_item_serial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitems',
            name='item_serial',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='inventoryproducts',
            name='product_serial',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
