# Generated by Django 4.1.2 on 2022-11-01 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_alter_inventoryitems_item_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
        migrations.DeleteModel(
            name='CheckoutItems',
        ),
    ]
